import type { Project } from '@/lib/types';

import { idx } from '@/lib/grid';

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildPatternPdfHtml(project: Project): string {
  const { name, width, height, design, palette } = project;
  const cell = 6;
  const rows: string[] = [];
  for (let y = 0; y < height; y++) {
    const cells: string[] = [];
    for (let x = 0; x < width; x++) {
      const c = design[idx(x, y, width)];
      const hex = c >= 0 ? palette[c]?.hex ?? '#eee' : '#f7f7f7';
      cells.push(`<td style="width:${cell}px;height:${cell}px;background:${hex};border:0.2px solid #ccc;"></td>`);
    }
    rows.push(`<tr>${cells.join('')}</tr>`);
  }

  const keyRows = palette
    .map((t, i) => {
      const count = design.filter((d) => d === i).length;
      if (count === 0) return '';
      return `<tr><td style="background:${esc(t.hex)};width:18px;"></td><td>${esc(t.dmc)}</td><td>${esc(
        t.name ?? '',
      )}</td><td>${count}</td></tr>`;
    })
    .filter(Boolean)
    .join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>${esc(name)}</title>
<style>
  body { font-family: system-ui, sans-serif; padding: 12px; color: #111; }
  h1 { font-size: 18px; margin: 0 0 8px; }
  table.pattern { border-collapse: collapse; margin: 8px 0 16px; }
  table.key { border-collapse: collapse; font-size: 11px; }
  table.key td { padding: 4px 8px; border: 1px solid #ddd; vertical-align: middle; }
</style></head><body>
  <h1>${esc(name)}</h1>
  <p style="font-size:12px;opacity:.8">${width} × ${height} stitches · generated by StitchCraft</p>
  <table class="pattern">${rows.join('')}</table>
  <h2 style="font-size:14px;">Colour key</h2>
  <table class="key"><thead><tr><th></th><th>DMC</th><th>Name</th><th>Count</th></tr></thead><tbody>${keyRows}</tbody></table>
</body></html>`;
}
